spring.application.name=auth-service

spring.security.oauth2.client.registration.facebook.client-id=471941452041863
spring.security.oauth2.client.registration.facebook.client-secret=a5607a83e426ca832c078080ab7d7faf
spring.security.oauth2.client.registration.facebook.scope=public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/facebook
spring.security.oauth2.client.registration.facebook.client-name=Facebook

spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v12.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v12.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email

